version: '3'
services:
  backend:
    container_name: backend
    build: .
    image: backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: backendDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      TZ: Europe/Moscow
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - backend
    depends_on:
      - backendDB

  backendDB:
    container_name: backendDB
    # platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Europe/Moscow
    volumes:
      - ./pg-data:/var/lib/postgresql/data/ # if you want to use a bind folder
    networks:
      - backend

  backendAdminer:
    container_name: backendAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=backendDB
    networks:
      - backend
    depends_on:
      - backendDB

  tl_sync:
    container_name: tl_sync
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    build:
      context: .
      dockerfile: ./tl_sync/Dockerfile
    volumes:
      - ./tl_sync:/code
    command: python main.py
    networks:
      - backend
    depends_on:
      - backendDB

networks:
  backend:
    name: Backend
    driver: bridge
